apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vnhs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-blur-tenant/rhtap-demo-app/hacbs-test-project-vnhs@sha256:e006366a933d52f41c3554ed1fbef26e8435ca076d20bc16a43ba84dc4b75230
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
